#!/usr/bin/env bun
/**
 * Agent Client Protocol (ACP) JSON-RPC 2.0 stdio server
 * Generated by Murmuration (ACP adapter) for murmur
 *
 * Conforms to https://agentclientprotocol.com/
 * Run via: bun .acp/server.ts  OR  node .acp/server.ts
 */

import { createInterface } from "node:readline";
import { readFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const manifestPath = join(__dirname, "manifest.json");
const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));

type JsonRpcRequest = {
  jsonrpc: "2.0";
  id?: string | number | null;
  method: string;
  params?: any;
};

type Session = {
  id: string;
  agent?: string;
  cwd?: string;
  createdAt: number;
  activeTurnId?: string | number | null;
};

const sessions = new Map<string, Session>();
let nextSessionId = 1;

function sendResponse(id: string | number | null | undefined, result: any): void {
  if (id === undefined || id === null) return;
  const msg = JSON.stringify({ jsonrpc: "2.0", id, result });
  process.stdout.write(msg + "\n");
}

function sendError(id: string | number | null | undefined, code: number, message: string, data?: any): void {
  if (id === undefined || id === null) return;
  const msg = JSON.stringify({ jsonrpc: "2.0", id, error: { code, message, data } });
  process.stdout.write(msg + "\n");
}

function sendNotification(method: string, params: any): void {
  const msg = JSON.stringify({ jsonrpc: "2.0", method, params });
  process.stdout.write(msg + "\n");
}

export function handleRequest(req: JsonRpcRequest): void {
  const { id, method, params } = req;

  switch (method) {
    case "initialize": {
      sendResponse(id, {
        protocolVersion: "2.0",
        serverInfo: manifest.server,
        capabilities: manifest.capabilities,
        agents: manifest.agents.map((a: any) => ({
          name: a.name,
          description: a.description,
          isSubagent: a.isSubagent,
        })),
      });
      break;
    }

    case "tools/list": {
      sendResponse(id, {
        tools: manifest.tools,
      });
      break;
    }

    case "session/new": {
      const sessionId = `sess_${nextSessionId++}_${Date.now()}`;
      const requestedAgent = params?.agent || manifest.agents[0]?.name;
      const session: Session = {
        id: sessionId,
        agent: requestedAgent,
        cwd: params?.cwd || process.cwd(),
        createdAt: Date.now(),
      };
      sessions.set(sessionId, session);
      sendResponse(id, {
        sessionId,
        agent: requestedAgent,
      });
      break;
    }

    case "session/list": {
      const list = [...sessions.values()].map((s) => ({
        sessionId: s.id,
        agent: s.agent,
        cwd: s.cwd,
        createdAt: s.createdAt,
      }));
      sendResponse(id, { sessions: list });
      break;
    }

    case "session/prompt": {
      const sessionId = params?.sessionId;
      const session = sessionId ? sessions.get(sessionId) : undefined;
      if (!session) {
        sendError(id, -32602, `Session "${sessionId}" not found`);
        break;
      }

      session.activeTurnId = id;
      const prompt = params?.prompt || "";
      const agentName = params?.agent || session.agent || "architect";

      // Send streaming update notification
      sendNotification("session/update", {
        sessionId,
        status: "processing",
        agent: agentName,
        message: `Agent "${agentName}" received prompt.`,
      });

      // Formulate turn response
      sendResponse(id, {
        status: "completed",
        sessionId,
        agent: agentName,
        text: `[ACP Turn Response for "${agentName}"] Processed turn for prompt: "${prompt}"`,
      });
      session.activeTurnId = null;
      break;
    }

    case "session/cancel": {
      const sessionId = params?.sessionId;
      const session = sessionId ? sessions.get(sessionId) : undefined;
      if (session && session.activeTurnId) {
        sendNotification("session/update", {
          sessionId,
          status: "cancelled",
          message: "Turn cancelled by client.",
        });
        session.activeTurnId = null;
      }
      sendResponse(id, { cancelled: true });
      break;
    }

    case "$/cancel_request": {
      // Per ACP / LSP spec, $/cancel_request is a notification
      const cancelId = params?.id;
      for (const s of sessions.values()) {
        if (s.activeTurnId === cancelId) {
          s.activeTurnId = null;
        }
      }
      break;
    }

    default: {
      sendError(id, -32601, `Method "${method}" not found`);
      break;
    }
  }
}

// Start stdio reader if executed directly
if (import.meta.main || process.argv[1]?.endsWith(".acp/server.ts")) {
  const rl = createInterface({
    input: process.stdin,
    output: process.stdout,
    terminal: false,
  });

  rl.on("line", (line) => {
    const trimmed = line.trim();
    if (!trimmed) return;
    try {
      const req = JSON.parse(trimmed) as JsonRpcRequest;
      handleRequest(req);
    } catch (err) {
      sendError(null, -32700, "Parse error: invalid JSON");
    }
  });
}
