import { join } from "node:path";
import { existsSync } from "node:fs";
import { chmod, mkdir, rm } from "node:fs/promises";

export type HookAction = "install" | "uninstall" | "status";

const HOOK_BEGIN = "# --- MURMUR HOOK BEGIN ---";
const HOOK_END = "# --- MURMUR HOOK END ---";

const HOOK_CONTENT = `${HOOK_BEGIN}
# Automatically generated by murmr hook install
if [ -d "murmur" ]; then
  if command -v murmr >/dev/null 2>&1; then
    murmr doctor || exit 1
  elif [ -x "./node_modules/.bin/murmr" ]; then
    ./node_modules/.bin/murmr doctor || exit 1
  elif command -v bun >/dev/null 2>&1; then
    bun run src/cli.ts doctor || exit 1
  elif command -v npx >/dev/null 2>&1; then
    npx murmr doctor || exit 1
  fi
fi
${HOOK_END}`;

export function getHookScript(existingContent?: string): string {
  if (!existingContent || existingContent.trim().length === 0) {
    return `#!/usr/bin/env sh\n\n${HOOK_CONTENT}\n`;
  }

  // If hook is already present, replace existing block
  if (existingContent.includes(HOOK_BEGIN) && existingContent.includes(HOOK_END)) {
    const regex = new RegExp(`${HOOK_BEGIN}[\\s\\S]*?${HOOK_END}`);
    return existingContent.replace(regex, HOOK_CONTENT);
  }

  // Prepend shebang if missing
  const hasShebang = existingContent.startsWith("#!");
  const prefix = hasShebang ? "" : "#!/usr/bin/env sh\n\n";
  const separator = existingContent.endsWith("\n") ? "\n" : "\n\n";
  return `${prefix}${existingContent}${separator}${HOOK_CONTENT}\n`;
}

export function stripHookScript(content: string): string {
  if (!content.includes(HOOK_BEGIN)) return content;
  const regex = new RegExp(`\\n?${HOOK_BEGIN}[\\s\\S]*?${HOOK_END}\\n?`, "g");
  return content.replace(regex, "\n").trim();
}

/** `murmr hook <install|uninstall|status>` — manages Git pre-commit verification hooks. */
export async function hookCommand(
  projectRoot: string,
  action: HookAction = "install",
): Promise<number> {
  const gitDir = join(projectRoot, ".git");
  if (!existsSync(gitDir)) {
    console.error("hook: not a git repository (.git directory not found).");
    return 1;
  }

  const hooksDir = join(gitDir, "hooks");
  const hookPath = join(hooksDir, "pre-commit");

  switch (action) {
    case "install": {
      await mkdir(hooksDir, { recursive: true });
      let existing = "";
      if (existsSync(hookPath)) {
        existing = await Bun.file(hookPath).text();
      }

      const updated = getHookScript(existing);
      await Bun.write(hookPath, updated);
      await chmod(hookPath, 0o755);
      console.log(`hook: installed git pre-commit hook at .git/hooks/pre-commit`);
      return 0;
    }

    case "uninstall": {
      if (!existsSync(hookPath)) {
        console.log("hook: pre-commit hook file does not exist.");
        return 0;
      }
      const existing = await Bun.file(hookPath).text();
      if (!existing.includes(HOOK_BEGIN)) {
        console.log("hook: murmur hook was not found in .git/hooks/pre-commit.");
        return 0;
      }

      const stripped = stripHookScript(existing);
      // If file only contains shebang or is empty, delete it
      if (!stripped || stripped === "#!/usr/bin/env sh" || stripped === "#!/bin/sh") {
        await rm(hookPath, { force: true });
        console.log("hook: removed .git/hooks/pre-commit.");
      } else {
        await Bun.write(hookPath, `${stripped}\n`);
        await chmod(hookPath, 0o755);
        console.log("hook: removed murmur check from .git/hooks/pre-commit.");
      }
      return 0;
    }

    case "status": {
      if (!existsSync(hookPath)) {
        console.log("hook: pre-commit hook is NOT installed.");
        return 1;
      }
      const existing = await Bun.file(hookPath).text();
      const installed = existing.includes(HOOK_BEGIN) && existing.includes(HOOK_END);
      if (installed) {
        console.log("hook: murmur pre-commit hook is installed and active.");
        return 0;
      } else {
        console.log("hook: .git/hooks/pre-commit exists, but murmur hook is NOT installed.");
        return 1;
      }
    }

    default: {
      console.error(`Unknown hook action "${action}". Valid: install, uninstall, status.`);
      return 1;
    }
  }
}
