import type {
  AgentDefinition,
  InstructionDefinition,
  PipelineDefinition,
  SkillDefinition,
  SubagentDefinition,
} from "../../schema/index.ts";
import { emitFrontmatterDoc, type YamlValue } from "../../util/yaml.ts";
import { pipelineRoster, renderPipelineProse } from "../pipelineProse.ts";
import type {
  CompileContext,
  EmittedFile,
  RuntimeCompiler,
} from "../RuntimeCompiler.ts";

function getPluginName(ctx: CompileContext): string {
  const raw = ctx.config.project?.name || "murmur";
  return raw.toLowerCase().replace(/[^a-z0-9_-]+/g, "-");
}

/**
 * Antigravity adapter — emits native Antigravity plugin customizations:
 *  - .agents/plugins/<pluginName>/plugin.json
 *  - .agents/plugins/<pluginName>/agents/<name>.md (with mainAgent, subagent, commandExecutionPolicy)
 *  - .agents/plugins/<pluginName>/skills/<name>/SKILL.md
 *  - .agents/plugins/<pluginName>/rules/<name>.md (with applyTo glob frontmatter)
 *  - AGENTS.md at root for broad compatibility
 */
export class AntigravityAdapter implements RuntimeCompiler {
  readonly id = "antigravity";

  private agentFrontmatter(
    agent: AgentDefinition,
    opts: { isMain: boolean; extra?: Record<string, YamlValue> } = { isMain: true },
  ): Record<string, YamlValue> {
    const fm: Record<string, YamlValue> = {
      name: agent.name,
      description: agent.description,
      mainAgent: opts.isMain,
      subagent: true,
      commandExecutionPolicy: "auto",
    };
    if (agent.tools.length) fm["tools"] = agent.tools;
    if (agent.agents.length) fm["agents"] = agent.agents;
    if (agent.model && agent.model.length) fm["model"] = agent.model;
    return { ...fm, ...(opts.extra ?? {}) };
  }

  compileAgent(agent: AgentDefinition, ctx: CompileContext): EmittedFile[] {
    const plugin = getPluginName(ctx);
    const fm = this.agentFrontmatter(agent, {
      isMain: agent.userInvocable ?? true,
    });
    return [
      {
        path: `.agents/plugins/${plugin}/agents/${agent.name}.md`,
        contents: emitFrontmatterDoc(fm, agent.role),
      },
    ];
  }

  compileSubagent(sub: SubagentDefinition, ctx: CompileContext): EmittedFile[] {
    const plugin = getPluginName(ctx);
    const fm = this.agentFrontmatter(sub, {
      isMain: sub.userInvocable ?? false,
      extra: {
        spawnTrigger: sub.spawn.trigger,
      },
    });
    return [
      {
        path: `.agents/plugins/${plugin}/agents/${sub.name}.md`,
        contents: emitFrontmatterDoc(fm, sub.role),
      },
    ];
  }

  compileSkill(skill: SkillDefinition, ctx: CompileContext): EmittedFile[] {
    const plugin = getPluginName(ctx);
    const fm: Record<string, YamlValue> = {
      name: skill.name,
      description: skill.description,
    };
    return [
      {
        path: `.agents/plugins/${plugin}/skills/${skill.name}/SKILL.md`,
        contents: emitFrontmatterDoc(fm, skill.body),
      },
    ];
  }

  compileInstruction(
    instruction: InstructionDefinition,
    ctx: CompileContext,
  ): EmittedFile[] {
    const plugin = getPluginName(ctx);
    const fm: Record<string, YamlValue> = {
      applyTo: instruction.applyTo,
    };
    return [
      {
        path: `.agents/plugins/${plugin}/rules/${instruction.name}.md`,
        contents: emitFrontmatterDoc(fm, instruction.rules),
      },
    ];
  }

  compilePipeline(
    pipeline: PipelineDefinition,
    ctx: CompileContext,
  ): EmittedFile[] {
    const plugin = getPluginName(ctx);
    const fm: Record<string, YamlValue> = {
      name: pipeline.name,
      description: pipeline.description,
      mainAgent: true,
      subagent: true,
      commandExecutionPolicy: "auto",
      agents: pipelineRoster(pipeline),
    };
    return [
      {
        path: `.agents/plugins/${plugin}/agents/${pipeline.name}.md`,
        contents: emitFrontmatterDoc(fm, renderPipelineProse(pipeline)),
      },
    ];
  }

  finalize(ctx: CompileContext): EmittedFile[] {
    const plugin = getPluginName(ctx);
    const pluginJson: Record<string, YamlValue> = {
      name: ctx.config.project.name || "Murmur",
    };
    if (ctx.config.project.description) {
      pluginJson["description"] = ctx.config.project.description;
    }

    const lines: string[] = [
      `# ${ctx.config.project.name} — Agent Roster`,
      "",
      "Generated by Murmur (Antigravity target).",
      "",
      "## Main Agents",
      "",
      ...ctx.ir.agents.map((a) => `- **${a.name}** — ${a.description}`),
    ];
    if (ctx.ir.subagents.length) {
      lines.push("", "## Subagents", "");
      lines.push(
        ...ctx.ir.subagents.map((s) => `- **${s.name}** — ${s.description}`),
      );
    }
    if (ctx.ir.skills.length) {
      lines.push("", "## Skills", "");
      lines.push(
        ...ctx.ir.skills.map((s) => `- **${s.name}** — ${s.description}`),
      );
    }

    return [
      {
        path: `.agents/plugins/${plugin}/plugin.json`,
        contents: `${JSON.stringify(pluginJson, null, 2)}\n`,
      },
      {
        path: "AGENTS.md",
        contents: `${lines.join("\n")}\n`,
      },
    ];
  }
}
