import type {
  AgentDefinition,
  InstructionDefinition,
  PipelineDefinition,
  SkillDefinition,
  SubagentDefinition,
} from "../../schema/index.ts";
import { emitFrontmatterDoc, type YamlValue } from "../../util/yaml.ts";
import { pipelineRoster, renderPipelineProse } from "../pipelineProse.ts";
import type {
  CompileContext,
  EmittedFile,
  RuntimeCompiler,
} from "../RuntimeCompiler.ts";

/**
 * Claude Code adapter — emits Claude Code customization files:
 *  - .claude/agents/<name>.md (subagents with role & frontmatter)
 *  - .claude/skills/<name>/SKILL.md
 *  - .claude/rules/<name>.md (scoped rules)
 *  - CLAUDE.md at the project root (mirroring roster & instructions)
 */
export class ClaudeAdapter implements RuntimeCompiler {
  readonly id = "claude";

  private agentFrontmatter(
    agent: AgentDefinition,
    extra: Record<string, YamlValue> = {},
  ): Record<string, YamlValue> {
    const fm: Record<string, YamlValue> = {
      name: agent.name,
      description: agent.description,
    };
    if (agent.tools.length) fm["tools"] = agent.tools;
    if (agent.model && agent.model.length) fm["model"] = agent.model[0];
    if (agent.dispatch) {
      fm["dispatch"] = {
        "invoke-when": agent.dispatch.invokeWhen,
        "skip-when": agent.dispatch.skipWhen,
        tasks: agent.dispatch.tasks,
      };
    }
    return { ...fm, ...extra };
  }

  compileAgent(agent: AgentDefinition): EmittedFile[] {
    const fm = this.agentFrontmatter(agent);
    return [
      {
        path: `.claude/agents/${agent.name}.md`,
        contents: emitFrontmatterDoc(fm, agent.role),
      },
    ];
  }

  compileSubagent(sub: SubagentDefinition): EmittedFile[] {
    const fm = this.agentFrontmatter(sub, {
      "spawn-trigger": sub.spawn.trigger,
    });
    return [
      {
        path: `.claude/agents/${sub.name}.md`,
        contents: emitFrontmatterDoc(fm, sub.role),
      },
    ];
  }

  compileSkill(skill: SkillDefinition): EmittedFile[] {
    const fm: Record<string, YamlValue> = {
      name: skill.name,
      description: skill.description,
    };
    return [
      {
        path: `.claude/skills/${skill.name}/SKILL.md`,
        contents: emitFrontmatterDoc(fm, skill.body),
      },
    ];
  }

  compileInstruction(instruction: InstructionDefinition): EmittedFile[] {
    const fm: Record<string, YamlValue> = {
      applyTo: instruction.applyTo,
    };
    return [
      {
        path: `.claude/rules/${instruction.name}.md`,
        contents: emitFrontmatterDoc(fm, instruction.rules),
      },
    ];
  }

  compilePipeline(pipeline: PipelineDefinition): EmittedFile[] {
    const fm: Record<string, YamlValue> = {
      name: pipeline.name,
      description: pipeline.description,
      agents: pipelineRoster(pipeline),
    };
    return [
      {
        path: `.claude/agents/${pipeline.name}.md`,
        contents: emitFrontmatterDoc(fm, renderPipelineProse(pipeline)),
      },
    ];
  }

  finalize(ctx: CompileContext): EmittedFile[] {
    const lines: string[] = [
      `# ${ctx.config.project.name} — Claude Code Project Guide`,
      "",
      "Generated by Murmuration (Claude Code target).",
      "",
      "## Available Agents",
      "",
      ...ctx.ir.agents.map((a) => `- **${a.name}** — ${a.description}`),
    ];
    if (ctx.ir.subagents.length) {
      lines.push("", "## Subagents", "");
      lines.push(...ctx.ir.subagents.map((s) => `- **${s.name}** — ${s.description}`));
    }
    if (ctx.ir.skills.length) {
      lines.push("", "## Skills", "");
      lines.push(...ctx.ir.skills.map((s) => `- **${s.name}** — ${s.description}`));
    }
    if (ctx.ir.instructions.length) {
      lines.push("", "## Scoped Rules", "");
      lines.push(
        ...ctx.ir.instructions.map((i) => `- **${i.name}** (\`${i.applyTo}\`)`),
      );
    }
    if (ctx.ir.tools && ctx.ir.tools.length) {
      lines.push("", "## Tools", "");
      lines.push(
        ...ctx.ir.tools.map((t) => `- **${t.name}** — ${t.description} (\`${t.command}\`)`),
      );
    }

    const emitted: EmittedFile[] = [
      { path: "CLAUDE.md", contents: `${lines.join("\n")}\n` },
    ];

    if (ctx.ir.tools && ctx.ir.tools.length) {
      const servers: Record<string, { command: string; args: string[]; env?: Record<string, string> }> = {};
      for (const t of ctx.ir.tools) {
        servers[t.name] = {
          command: t.command,
          args: t.args,
          ...(Object.keys(t.env).length ? { env: t.env } : {}),
        };
      }
      emitted.push({
        path: ".claude/mcp_config.json",
        contents: `${JSON.stringify({ mcpServers: servers }, null, 2)}\n`,
      });
    }

    return emitted;
  }
}
