import type {
  AgentDefinition,
  InstructionDefinition,
  PipelineDefinition,
  SkillDefinition,
  SubagentDefinition,
} from "../../schema/index.ts";
import { emitFrontmatterDoc, type YamlValue } from "../../util/yaml.ts";
import { pipelineRoster, renderPipelineProse } from "../pipelineProse.ts";
import type {
  CompileContext,
  EmittedFile,
  RuntimeCompiler,
} from "../RuntimeCompiler.ts";

/**
 * Cursor adapter — emits Cursor rules and customization files:
 *  - .cursor/rules/<name>.mdc (MDC format with description, globs, alwaysApply)
 *  - .cursor/agents/<name>.md
 *  - .cursor/skills/<name>/SKILL.md
 *  - AGENTS.md at root
 */
export class CursorAdapter implements RuntimeCompiler {
  readonly id = "cursor";

  compileAgent(agent: AgentDefinition): EmittedFile[] {
    const fm: Record<string, YamlValue> = {
      name: agent.name,
      description: agent.description,
    };
    if (agent.tools.length) fm["tools"] = agent.tools;
    if (agent.dispatch) {
      fm["dispatch"] = {
        "invoke-when": agent.dispatch.invokeWhen,
        "skip-when": agent.dispatch.skipWhen,
        tasks: agent.dispatch.tasks,
      };
    }
    return [
      {
        path: `.cursor/agents/${agent.name}.md`,
        contents: emitFrontmatterDoc(fm, agent.role),
      },
    ];
  }

  compileSubagent(sub: SubagentDefinition): EmittedFile[] {
    const fm: Record<string, YamlValue> = {
      name: sub.name,
      description: sub.description,
      "spawn-trigger": sub.spawn.trigger,
    };
    if (sub.dispatch) {
      fm["dispatch"] = {
        "invoke-when": sub.dispatch.invokeWhen,
        "skip-when": sub.dispatch.skipWhen,
        tasks: sub.dispatch.tasks,
      };
    }
    return [
      {
        path: `.cursor/agents/${sub.name}.md`,
        contents: emitFrontmatterDoc(fm, sub.role),
      },
    ];
  }

  compileSkill(skill: SkillDefinition): EmittedFile[] {
    const fm: Record<string, YamlValue> = {
      name: skill.name,
      description: skill.description,
    };
    const files: EmittedFile[] = [
      {
        path: `.cursor/skills/${skill.name}/SKILL.md`,
        contents: emitFrontmatterDoc(fm, skill.body),
      },
    ];
    if (skill.assets) {
      for (const a of skill.assets) {
        files.push({
          path: `.cursor/skills/${skill.name}/${a.relativePath}`,
          contents: a.contents ?? "",
        });
      }
    }
    return files;
  }

  compileInstruction(instruction: InstructionDefinition): EmittedFile[] {
    const fm: Record<string, YamlValue> = {
      description: `Rules for ${instruction.name}`,
      globs: instruction.applyTo,
      alwaysApply: instruction.applyTo === "**/*" || instruction.applyTo === "*",
    };
    return [
      {
        path: `.cursor/rules/${instruction.name}.mdc`,
        contents: emitFrontmatterDoc(fm, instruction.rules),
      },
    ];
  }

  compilePipeline(pipeline: PipelineDefinition): EmittedFile[] {
    const fm: Record<string, YamlValue> = {
      name: pipeline.name,
      description: pipeline.description,
      agents: pipelineRoster(pipeline),
    };
    return [
      {
        path: `.cursor/agents/${pipeline.name}.md`,
        contents: emitFrontmatterDoc(fm, renderPipelineProse(pipeline)),
      },
    ];
  }

  finalize(ctx: CompileContext): EmittedFile[] {
    const lines: string[] = [
      `# ${ctx.config.project.name} — Cursor Agent Roster`,
      "",
      "Generated by Murmuration (Cursor target).",
      "",
      "## Agents",
      "",
      ...ctx.ir.agents.map((a) => `- **${a.name}** — ${a.description}`),
    ];
    if (ctx.ir.subagents.length) {
      lines.push("", "## Subagents", "");
      lines.push(...ctx.ir.subagents.map((s) => `- **${s.name}** — ${s.description}`));
    }
    return [{ path: "AGENTS.md", contents: `${lines.join("\n")}\n` }];
  }
}
